Status: {
  "tf": "error"
}
Traceback (most recent call last):
  File "/seamless/seamless/core/execute.py", line 69, in _execute
    exec_code(
  File "/seamless/seamless/core/cached_compile.py", line 63, in exec_code
    exec(code_obj, namespace)
  File "Seamless transformer: .tf", line 2, in <module>
    print('TEST'); raise Exception(a)
Exception: 1

*************************************************
* Standard output
*************************************************
TEST

*************************************************

Status: OK
None
OK
