seamless: Upload 1 files, total 36.00 B
seamless.core.transformation.SeamlessTransformationError: Error 400 from assistant:ERROR: Unknown error
Output:
Traceback (most recent call last):
  File "/home/jovyan/seamless-scripts/run-transformation.py", line 152, in <module>
    result = seamless.run_transformation(checksum.bytes(), fingertip=fingertip, tf_dunder=dunder, scratch=scratch, manager=manager)
  File "/seamless/seamless/__init__.py", line 113, in run_transformation
    return tf_cache.run_transformation(checksum, fingertip=fingertip, scratch=scratch, tf_dunder=tf_dunder, new_event_loop=new_event_loop, manager=manager)
  File "/seamless/seamless/core/cache/transformation_cache.py", line 1270, in run_transformation
    asyncio.get_event_loop().run_until_complete(fut)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/seamless/seamless/core/cache/transformation_cache.py", line 1215, in run_transformation_async
    raise self.transformation_exceptions[tf_checksum]
seamless.core.transformation.SeamlessTransformationError: 
Bash transformer exception
==========================

Error: Return code 127

*************************************************
* Command
*************************************************
(
headify workfiles/text.txt -n 3
) > RESULT
*************************************************


*************************************************
* Standard output
*************************************************
/bin/bash: line 4: headify: command not found

*************************************************
*************************************************
Execution time: 0.0 seconds


buffer cache, 6 buffers undestroyed
filelist.txt
numbers.dat
table.csv
text.txt

cat: workfiles/text-head.txt: No such file or directory

seamless: Upload 1 files, total 22.00 B
seamless.core.transformation.SeamlessTransformationError: Error 400 from assistant:ERROR: Unknown error
Output:
Traceback (most recent call last):
  File "/home/jovyan/seamless-scripts/run-transformation.py", line 152, in <module>
    result = seamless.run_transformation(checksum.bytes(), fingertip=fingertip, tf_dunder=dunder, scratch=scratch, manager=manager)
  File "/seamless/seamless/__init__.py", line 113, in run_transformation
    return tf_cache.run_transformation(checksum, fingertip=fingertip, scratch=scratch, tf_dunder=tf_dunder, new_event_loop=new_event_loop, manager=manager)
  File "/seamless/seamless/core/cache/transformation_cache.py", line 1270, in run_transformation
    asyncio.get_event_loop().run_until_complete(fut)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/seamless/seamless/core/cache/transformation_cache.py", line 1215, in run_transformation_async
    raise self.transformation_exceptions[tf_checksum]
seamless.core.transformation.SeamlessTransformationError: 
Bash transformer exception
==========================

Error: Return code 127

*************************************************
* Command
*************************************************
(
headify workfiles/filelist.txt -n 3 --batch
) > RESULT
*************************************************


*************************************************
* Standard output
*************************************************
/bin/bash: line 4: headify: command not found

*************************************************
*************************************************
Execution time: 0.0 seconds


buffer cache, 6 buffers undestroyed
filelist.txt
numbers.dat
table.csv
text.txt

cat: numbers-head.dat: No such file or directory

cat: table-head.csv: No such file or directory

