   ...:     print("START")
   ...:     raise Exception # deliberately
   ...: try:
   ...:     func0(0,0)
   ...: except SeamlessTransformationError:
   ...:     traceback.print_exc(1)
   ...: print("/exception")
   ...: print()
   ...:         
In [2]: # %load imperative-jupyter.py
   ...: from seamless.imperative import transformer
   ...: from seamless.core.transformation import SeamlessTransformationError
   ...: import traceback
   ...: 
   ...: @transformer
   ...: def func(a, b):
   ...:     import time
   ...:     time.sleep(0.5)
   ...:     return 100 * a + b
   ...: func = transformer(func)
   ...: 
   ...: result = func(88, 17) # takes 0.5 sec
   ...: print(result)
   ...: result = func(88, 17) # immediate
   ...: print(result)
   ...: result = func(21, 17) # immediate
   ...: print(result)
   ...: 
   ...: print("The following will give an exception:")
   ...: @transformer
   ...: def func0(a, b):
   ...:     print("START")
   ...:     raise Exception # deliberately
   ...: try:
   ...:     func0(0,0)
   ...: except SeamlessTransformationError:
   ...:     traceback.print_exc(1)
   ...: print("/exception")
   ...: print()
   ...: 
8817
8817
2117
The following will give an exception:
/exception

Traceback (most recent call last):
  File "/tmp/ipykernel_118773/1315377767.py", line 26, in <module>
    func0(0,0)
seamless.core.transformation.SeamlessTransformationError: Traceback (most recent call last):
  File "<seamless.core.cache.transformation_cache.DummyTransformer object at 0x7f8b91e348b0>", line 6, in <module>
    result = func0(a=a,b=b)
  File "<seamless.core.cache.transformation_cache.DummyTransformer object at 0x7f8b91e348b0>", line 4, in func0
    raise Exception # deliberately
Exception

*************************************************
* Standard output
*************************************************
START

*************************************************
*************************************************
Execution time: 0.0 seconds

In [3]: exit()              
In [3]: exit()
Shutting down kernel
